version: "3.3"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8088:80
    links:
      - phpfpm
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log

  phpfpm:
    image: php:fpm-alpine
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./public:/usr/share/nginx/html

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080